version: '3.7'

services:
  apache:
    build: './apache'
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ../dist_local:/usr/local/apache2/htdocs
    depends_on:
      - php
      - mysql
    restart: always

  php:
    build: './php'
    volumes:
      - ../dist_local:/usr/local/apache2/htdocs
    restart: always

  mysql:
    build: './mysql'
    ports:
      - 3306:3306
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./volumes/db_init:/docker-entrypoint-initdb.d
    restart: always

  # node:
  #   build: './node'
  #   # image: node:13.8
  #   user: 'node'
  #   working_dir: /home/node/app
  #   volumes:
  #     - ..:/home/node/app
  #   command: 'npm run webpack' # comment this line if you want to serve but not build
  #   restart: always # comment this line if you want to serve but not build
  #   # command: 'npm --version' # UNcomment this line if you want to serve but not build