name: Doenet CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prettify
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --write ./src/**/*.{jsx,json,php}
          prettier_plugins: '@prettier/plugin-php'
          dry: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node_version: '14'

      - name: Deps install
        run: npm install
      - name: Lint
        run: npx eslint "./src/**/*.{jsx,js}"
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create cache
        uses: actions/cache@v2
        id: npm-and-build-cache
        with:
          path: |
            ~/.cache/Cypress
            dist_ci
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - name: Install cypress
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          build: npm run build:ci
  ui-tests:
    name: ${{ matrix.browser }} tests
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrive cache
        uses: actions/cache@v2
        id: npm-and-build-cache
        with:
          path: |
            ~/.cache/Cypress
            dist_local
            node_modules
          key: ${{ runner.os }}-node_modules-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-build-
      - name: Cypress ${{ matrix.browser }} run
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: npm run start:ci
          wait-on: 'http://localhost'
          wait-on-timeout: 180
          browser: ${{matrix.browser}}
          headless: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
